# Disable sudo to speed up the build
sudo: false
language: python
install:
  - pip install tox flake8 codecov
matrix:
  include:
    - python: "3.5"
      env: TOX_ENVS=py35-django22
    - python: "3.6"
      dist: xenial
      env: TOX_ENVS=py36-django22,py36-django30,py36-django31
    - python: "3.7"
      env: TOX_ENVS=py37-django22,py37-django30,py37-django31
      dist: xenial
    - python: "3.8"
      env: TOX_ENVS=py38-django22,py38-django30,py38-django31
    - python: "3.9-dev"
      env: TOX_ENVS=py39-django22,py39-django30,py39-django31
before_script:
  - flake8 . --count
script:
  - tox -e $TOX_ENVS
after_success:
  - codecov
deploy:
  provider: pypi
  user: eshaan7
  password: testpasswordfortravis
  on:
    tags: true
    repo: eshaan7/django-rest-durin
  only:
    - main
  distributions: "sdist bdist_wheel"
git:
  depth: false
